# Generated by Django 2.1.2 on 2021-07-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas_carreras',
            old_name='carrea',
            new_name='carrera',
        ),
    ]
