# Generated by Django 2.1.2 on 2021-08-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrera', '0001_initial'),
        ('Usuario', '0002_alumno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera'),
        ),
    ]
