# Generated by Django 2.1.2 on 2021-08-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0012_auto_20210811_2051'),
        ('Tema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
