# Generated by Django 2.1.2 on 2021-08-06 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '__first__'),
        ('Usuario', '__first__'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('is_private', models.BooleanField(blank=True, default=True, null=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Persona')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Estado_rubrica')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Topico_rubricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Rubrica')),
                ('topico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tema.Topico')),
            ],
        ),
        migrations.AddField(
            model_name='rubrica',
            name='topico',
            field=models.ManyToManyField(blank=True, related_name='Topico_rubricas', through='Rubrica.Topico_rubricas', to='Tema.Topico'),
        ),
    ]
