# Generated by Django 2.1.2 on 2021-08-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_auto_20210805_2120'),
        ('Rubrica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
    ]
