# Generated by Django 2.1.2 on 2021-08-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0003_auto_20210810_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
