# Generated by Django 2.1.2 on 2021-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0004_auto_20210810_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
