# Generated by Django 2.1.2 on 2021-08-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0005_auto_20210810_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Estado_rubrica'),
        ),
    ]
