# Generated by Django 2.1.2 on 2021-08-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0007_auto_20210811_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Tipo_rubrica'),
        ),
    ]
