# Generated by Django 2.1.2 on 2021-08-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0008_auto_20210811_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Rubrica'),
        ),
    ]
