# Generated by Django 2.1.2 on 2021-08-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0010_auto_20210811_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
