# Generated by Django 2.1.2 on 2021-08-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0011_auto_20210811_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='topico',
        ),
        migrations.AlterField(
            model_name='topico_rubricas',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Topico'),
        ),
        migrations.AddField(
            model_name='topico',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Rubrica'),
        ),
    ]
