# Generated by Django 2.1.2 on 2021-08-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0012_auto_20210811_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Topico'),
        ),
    ]
