# Generated by Django 2.1.2 on 2021-08-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0013_puntaje_topico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntaje',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='puntaje',
        ),
    ]
