# Generated by Django 2.1.2 on 2021-09-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0014_auto_20210827_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='estado',
            field=models.CharField(default='Sin Definir', max_length=20),
        ),
    ]
