# Generated by Django 2.1.2 on 2021-09-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0015_topico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_aspecto',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
