# Generated by Django 2.1.2 on 2021-09-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0003_alumno_carrera'),
        ('Rubrica', '0016_calificacion_aspecto_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspectos_Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion_Aspectos_Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Aspectos_Coevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluar_Alumnos_Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(choices=[('1 INSUFICIENTE', ' 1'), ('2 SUFICIENTE', ' 2'), ('3 BUENO', ' 3'), ('4 EXCELENTE', ' 4')], default='1 INSUFICIENTE', max_length=100)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Alumno')),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Descripcion_Aspectos_Coevaluacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
