# Generated by Django 2.1.2 on 2021-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0017_aspectos_coevaluacion_descripcion_aspectos_coevaluacion_evaluar_alumnos_coevaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectos_coevaluacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
