# Generated by Django 2.1.2 on 2021-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0018_auto_20210922_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_aspectos_coevaluacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
