# Generated by Django 2.1.2 on 2021-09-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0019_auto_20210922_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion_Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='descripcion_aspectos_coevaluacion',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Calificacion_Coevaluacion'),
        ),
    ]
