# Generated by Django 2.1.2 on 2021-09-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0010_auto_20210920_2113'),
        ('Rubrica', '0020_auto_20210922_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluar_alumnos_coevaluacion',
            old_name='aspecto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='evaluar_alumnos_coevaluacion',
            name='evaluacion',
        ),
        migrations.AddField(
            model_name='evaluar_alumnos_coevaluacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Grupos_Alumnos'),
        ),
    ]
