# Generated by Django 2.1.2 on 2021-09-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0010_auto_20210920_2113'),
        ('Rubrica', '0021_auto_20210922_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluar_alumnos_coevaluacion',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion'),
        ),
    ]
