# Generated by Django 2.1.2 on 2021-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0022_evaluar_alumnos_coevaluacion_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_coevaluacion',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
