# Generated by Django 2.1.2 on 2021-09-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0023_calificacion_coevaluacion_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluar_alumnos_coevaluacion',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Calificacion_Coevaluacion'),
        ),
    ]
