# Generated by Django 2.1.2 on 2021-09-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0024_evaluar_alumnos_coevaluacion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluar_alumnos_coevaluacion',
            name='aspectos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Aspectos_Coevaluacion'),
        ),
    ]
