# Generated by Django 2.1.2 on 2021-09-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0025_evaluar_alumnos_coevaluacion_aspectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluar_alumnos_coevaluacion',
            name='aspectos',
        ),
        migrations.RemoveField(
            model_name='evaluar_alumnos_coevaluacion',
            name='calificacion',
        ),
    ]
