# Generated by Django 2.1.2 on 2021-09-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0026_auto_20210922_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectos_coevaluacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
