# Generated by Django 2.1.2 on 2021-09-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0027_aspectos_coevaluacion_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluar_alumnos_coevaluacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evaluar_alumnos_coevaluacion',
            name='opinion',
            field=models.CharField(choices=[('1', ' 1'), ('2', ' 2'), ('3', ' 3'), ('4', ' 4')], default='2', max_length=100),
        ),
    ]
