# Generated by Django 2.1.2 on 2021-09-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0028_auto_20210922_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Califica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluar_alumnos_coevaluacion',
            name='opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Califica'),
        ),
    ]
