# Generated by Django 2.1.2 on 2021-09-23 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rubrica', '0029_auto_20210922_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='rubrica',
        ),
        migrations.RemoveField(
            model_name='topico_rubricas',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='calificacion_aspecto',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Rubrica'),
        ),
        migrations.AddField(
            model_name='calificacion_aspecto',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topico_rubricas',
            name='ponderacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
