# Generated by Django 2.1.2 on 2021-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0030_auto_20210923_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_coevaluacion',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
