# Generated by Django 2.1.2 on 2021-09-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0032_aplicar_rubrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicar_rubrica',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
