# Generated by Django 2.1.2 on 2021-09-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0013_grupos_flag'),
        ('Rubrica', '0033_aplicar_rubrica_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicar_rubrica',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Grupos_Alumnos'),
        ),
    ]
