# Generated by Django 2.1.2 on 2021-09-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0013_grupos_flag'),
        ('Rubrica', '0035_auto_20210930_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicar_RubricaGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True)),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Topico')),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Calificacion_aspecto')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Grupos')),
                ('rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rubrica.Rubrica')),
            ],
        ),
    ]
