# Generated by Django 2.1.2 on 2021-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrica', '0037_evaluar_alumnos_coevaluacion_aspecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='califica',
            name='ponderacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
