# Generated by Django 2.1.2 on 2021-08-06 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura_alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2, null=True)),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('alumno', models.ManyToManyField(blank=True, related_name='Asignatura_alumnos', through='Curso.Asignatura_alumnos', to='Usuario.Alumno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Asignatura')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ponderacion', models.IntegerField(blank=True, null=True)),
                ('is_grupal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Alumno')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_en_Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('alumno', models.ManyToManyField(blank=True, null=True, to='Usuario.Alumno')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='alumno',
            field=models.ManyToManyField(blank=True, related_name='Evaluacion_alumnos', through='Curso.Evaluacion_alumnos', to='Usuario.Alumno'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Tipo_evaluacion'),
        ),
        migrations.AddField(
            model_name='asignatura_alumnos',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
        migrations.AddField(
            model_name='asignatura_alumnos',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Evaluacion_alumnos'),
        ),
    ]
