# Generated by Django 2.1.2 on 2021-08-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura_alumnos',
            old_name='asignatura',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='asignatura',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='asignatura',
            new_name='curso',
        ),
    ]
