# Generated by Django 2.1.2 on 2021-08-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_auto_20210805_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso_Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso_Paralelo'),
        ),
    ]
