# Generated by Django 2.1.2 on 2021-07-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_curso_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
    ]
