# Generated by Django 2.1.2 on 2021-08-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_auto_20210805_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_evaluacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
