# Generated by Django 2.1.2 on 2021-09-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alumno_carrera'),
        ('Curso', '0005_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo_en_evaluacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grupo_en_evaluacion',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='is_grupal',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='grupo_en_evaluacion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='grupo_en_evaluacion',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Alumno'),
        ),
        migrations.AddField(
            model_name='grupo_en_evaluacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Grupos'),
        ),
    ]
