# Generated by Django 2.1.2 on 2021-09-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrera', '0001_initial'),
        ('Curso', '0006_auto_20210914_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
    ]
