# Generated by Django 2.1.2 on 2021-09-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alumno_carrera'),
        ('Curso', '0008_archivo_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos_Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Alumno')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Asignatura')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo_en_evaluacion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='grupo_en_evaluacion',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='grupo_en_evaluacion',
            name='grupo',
        ),
        migrations.AddField(
            model_name='grupos',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Asignatura'),
        ),
        migrations.DeleteModel(
            name='Grupo_en_Evaluacion',
        ),
        migrations.AddField(
            model_name='grupos_alumnos',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Grupos'),
        ),
    ]
