# Generated by Django 2.1.2 on 2021-09-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0009_auto_20210920_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_alumnos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso'),
        ),
        migrations.AlterField(
            model_name='archivo_notas',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='notas_alumnos/%Y/%m/%d/'),
        ),
    ]
