# Generated by Django 2.1.2 on 2021-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0010_auto_20210920_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura_alumnos',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
