# Generated by Django 2.1.2 on 2021-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0012_grupos_alumnos_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
