# Generated by Django 2.1.2 on 2021-08-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alumno_carrera'),
        ('RA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ra',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Persona'),
        ),
    ]
