# Generated by Django 2.1.2 on 2021-08-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0002_ra_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ra',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
